/**
 * This file is the single point of entry for all Genkit flow requests.
 * It is automatically generated by the Genkit CLI.
 *
 * You can edit this file to add authentication, logging, etc.
 * See https://genkit.dev/docs/flow/production#securing-your-flows
 */

import { genkit } from 'genkit';
import {googleAI} from '@genkit-ai/google-genai';

// Initialize the AI instance for all flows.
// Make sure to configure any plugins used by your flows.
genkit({
  plugins: [googleAI()],
  model: 'googleai/gemini-2.5-pro',
});

// Import all the flow definitions.
import '@/ai/flows/generate-meal-ideas-from-ingredients.ts';
import '@/ai/flows/generate-7-day-meal-plan.ts';
import '@/ai/flows/generate-quick-meal-ideas.ts';
import '@/ai/flows/generate-meal-idea.ts';
import '@/ai/flows/identify-ingredients-from-image.ts';

// Expose the Genkit API endpoint.
import { nextHandler } from '@genkit-ai/next';
export const POST = nextHandler();
