import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function TermsPage() {
  return (
    <div className="w-full max-w-2xl mx-auto space-y-8">
      <div className="text-center">
        <h1 className="text-4xl font-bold font-headline">Terms & Conditions</h1>
        <p className="text-muted-foreground mt-2">
          Last updated: {new Date().toLocaleDateString()}
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Agreement to Terms</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-muted-foreground">
          <p>
            By using our application, you agree to be bound by these Terms & Conditions. If you do not agree to these terms, please do not use the application.
          </p>
          
          <h3 className="font-semibold text-lg pt-4">Use of Service</h3>
          <p>
            MealGenna is provided to assist you in generating meal ideas. You agree not to use the app for any illegal or unauthorized purpose.
          </p>

          <h3 className="font-semibold text-lg pt-4">Content</h3>
          <p>
            Our service allows you to generate recipes and other content. The recipes and nutritional information are generated by an AI and should be used as a guideline. Always use your best judgment when cooking and handling food.
          </p>

          <h3 className="font-semibold text-lg pt-4">Termination</h3>
          <p>
            We may terminate or suspend your access to our service at any time, without prior notice, for any reason, including without limitation if you breach the Terms.
          </p>

           <h3 className="font-semibold text-lg pt-4">Changes to Terms</h3>
          <p>
            We reserve the right to modify these terms at any time. We will notify you of any changes by posting the new Terms & Conditions on this page.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
