require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

# 1. Bump to iOS 15.0 to satisfy AdMob requirements
platform :ios, '15.0'

# 2. Use Static Linking (Required for AdMob + Firebase)
use_frameworks! :linkage => :static

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
  pod 'CapacitorFirebaseAnalytics', :path => '../../node_modules/@capacitor-firebase/analytics'
end

target 'App' do
  capacitor_pods
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 3. Force 15.0 here as well
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end