name: App
options:
  bundleIdPrefix: com.nesberry.mealgenna.pro
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: App
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: 5BYJT9QTKZ
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "MealGenna Pro Store"
        PRODUCT_BUNDLE_IDENTIFIER: com.nesberry.mealgenna.pro
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: "MealGenna Pro Store"
        Release:
          PROVISIONING_PROFILE_SPECIFIER: "MealGenna Pro Store"
    postCompileScripts:
      - path: ../../../node_modules/@capacitor/ios/scripts/pods_helpers.rb
        name: "Run Capacitor Pods Script"

  App-Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AppTests
    dependencies:
      - target: App
